import { readFileSync } from "node:fs";
import vm from "node:vm";

export function loadRegistry() {
  const source = readFileSync(new URL("./registry.js", import.meta.url), "utf8");
  const context = vm.createContext({});
  vm.runInContext(source, context, { filename: "registry.js" });
  return {
    registry: Array.from(context.PROTOTYPE_REGISTRY, (entry) => ({ ...entry, themeCoverage: [...entry.themeCoverage], components: [...entry.components] })),
    meta: {
      ...context.PROTOTYPE_REGISTRY_META,
      consolidated: Array.from(context.PROTOTYPE_REGISTRY_META.consolidated, (item) => ({ ...item })),
    },
  };
}

const cell = (value) => String(value).replaceAll("|", "\\|").replaceAll("\n", " ");

export function renderMatrix(registry, meta) {
  const counts = Object.fromEntries(["surface", "state", "overlay", "qa"].map((kind) => [kind, registry.filter((entry) => entry.classification === kind).length]));
  const rows = registry.map((entry) => `| ${cell(entry.id)} | ${cell(entry.parent)} | ${cell(entry.label)} | ${entry.classification.toUpperCase()} | ${cell(entry.trigger)} | ${entry.userVisible ? "yes" : "no"} | ${entry.reviewOnly ? "yes" : "no"} | ${entry.themeCoverage.join(" / ")} | ${cell(entry.snapshotId)} |`);
  return `# Phase 5B Screen/State Matrix

Generated from [registry.js](registry.js) by \`node generate-matrix.mjs --check\`. Do not edit this file directly.

The current images are regression anchors only. They are not user approval of the design.

## Frozen hierarchy

- Canonical app surfaces (A): ${counts.surface}
- Meaningful screen states/variants (B): ${counts.state}
- Overlays/sheets/menus/confirmations (C): ${counts.overlay}
- QA/review-only entries (D): ${counts.qa}
- Total review entries: ${registry.length} (baseline before stabilization: ${meta.baselineCount})

## Matrix

| Review ID | Canonical surface / parent | State or variant | Class | Trigger/path | User-visible | Review-only | Theme coverage | Snapshot ID |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows.join("\n")}
`;
}
